### ISSUE TITLE
Themr Won't Forget Theme Settings

### ISSUE THREAD

**Issue by bcrotty** [benweier/Themr#14]
I can't figure out how to reset Themr's watched theme settings. Whenever I remove a setting from _**Preferences.sublime-settings**_ and then change the theme, the setting comes back. I tried using the `themr_watch_settings` flag, but it does not seem to change the behavior whether `true` or `false`.

**Comment by benweier** [comment]
That's very interesting @bcrotty I'll look into it

**Comment by benweier** [comment]
@bcrotty this should be fixed now. The issue was that I was loading the preferences file on package initialisation and it wasn't being updated when settings changed. I've also removed `themr_watch_settings` to simplified the logic a little and avoid confusion about what it does.

**Comment by bcrotty** [comment]
@benweier Should the changes be live? When I delete a line from my Preferences.sublime-settings and then change the theme, it still brings the line back. Package Control upgraded all the packages it knew about.

**Comment by benweier** [comment]
It can take some time for the change to be picked up. The Package Control page is showing the last modified time and I've just run a Package Control update and it has fetched the latest Themr and Schemr. Remember to restart Sublime to reinitialise the package too

**Comment by bcrotty** [comment]
It's still not working for me. I removed Themr, restarted Sublime, installed Themr. I have a bunch of settings in my user preferences, such as ```"material_theme_tabs_autowidth": false,```. When I delete that line, save the file, and hit Ctrl+F8, the line comes back.

**Comment by bcrotty** [comment]
I can successfully remove a setting if I delete the line, save the user preferences file, and restart Sublime before I change the theme. But if I try to change the theme before I restart Sublime, it will put the user preferences back to what it was, either adding or removing content to get it back to what it was.

**Comment by benweier** [comment]
Thanks for your patience @bcrotty. I can't replicate this with Sublime Text 3 build 3102 on OS X El Capitan. Could you provide your ST version and OS?

**Comment by bcrotty** [comment]
Thanks for Themr! ST3 Build 3103 on Windows 10 & Windows 8.1.

**Comment by benweier** [comment]
I'll try some testing on Windows today

**Comment by benweier** [comment]
I've spent some time trying different sequences of actions with ST 3 b3103 on Windows 10 to trigger the issue and I can't replicate it.

Could you look into one other thing for me. Open the ST console with <kbd>ctrl+`</kbd> and change the theme. You'll notice a line that says `reloading /C/Users/user/AppData/Roaming/Sublime Text 3/Packages/User/Prefences.sublime-settings`

Themr should only be performing a single modification to the `Prefences.sublime-settings` file so if you see that line multiple times it means another package is performing an update to your settings as well. It could be the cause of problem. Have you changed settings with another package to see if it's isolated to just Themr?

**Comment by bcrotty** [comment]
I disabled everything (including Package Control) except Themr and Theme - Soda, and it still happens. There is a single modification of `Preferences.sublime-settings`.

My sequence of steps is:
- Launch Sublime
- Delete any line from `Preferences.sublime-settings`
- Save `Preferences.sublime-settings`
- Hit Ctrl+F8

At this point, the Preferences.sublime-settings reloads back to what it was when I launched Sublime.
